//
//  MessagesViewController.m
//  MessagesExtension
//
//  Created by Gopal Rao Gurram on 3/9/17.
//  Copyright © 2017 Gopal Rao Gurram. All rights reserved.
//

#import "MessagesViewController.h"


@interface MessagesViewController ()

@property (nonatomic, strong) UALBaseMessageViewController *baseMessageViewController;

@property (nonatomic, strong) UALFlightStatusMainViewController *flightStatusController;

@end

@implementation MessagesViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma mark - Conversation Handling

-(void)willBecomeActiveWithConversation:(MSConversation *)conversation {
    
    [self presentViewControllerForconversation: conversation withPresentationStyle: self.presentationStyle];
}

-(void)willTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    // Called before the extension transitions to a new presentation style.
    
    // Use this method to prepare for the change in presentation style.
}


-(void)didBecomeActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the inactive to active state.
    // This will happen when the extension is about to present UI.
    
    // Use this method to configure the extension and restore previously stored state.
}

-(void)willResignActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the active to inactive state.
    // This will happen when the user dissmises the extension, changes to a different
    // conversation or quits Messages.
    
    // Use this method to release shared resources, save user data, invalidate timers,
    // and store enough state information to restore your extension to its current state
    // in case it is terminated later.
}

-(void)didReceiveMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when a message arrives that was generated by another instance of this
    // extension on a remote device.
    
    // Use this method to trigger UI updates in response to the message.
}

-(void)didStartSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user taps the send button.
}

-(void)didCancelSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user deletes the message without sending it.
    
    // Use this to clean up state related to the deleted message.
}


-(void)didTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    // Called after the extension transitions to a new presentation style.
    
    // Use this method to finalize any behaviors associated with the change in presentation style.
    MSConversation *conversation = self.activeConversation? self.activeConversation: nil;
    [self presentViewControllerForconversation: conversation withPresentationStyle: self.presentationStyle];
}

# pragma mark -

- (void) presentViewControllerForconversation:(MSConversation *)conversation withPresentationStyle: (MSMessagesAppPresentationStyle)presentationStyle{
    
    for (UIView *childVw in self.messagesView.subviews) {
        
        [childVw removeFromSuperview];
    }
    
    // Determine the controller to present.
    UIViewController *controller = [UIViewController new];
    
    //controller = [self instantiateFlightStatusMainViewController];
    
    
    if (presentationStyle == MSMessagesAppPresentationStyleCompact) {
        
        controller = [self instantiateBaseMessageViewController];
    }
    else{
        
        controller = [self instantiateFlightStatusMainViewController];
    }
    
    [self.messagesView addSubview: controller.view];
    [self addChildViewController: controller];
    [controller didMoveToParentViewController: self];
    
    controller.view.frame = CGRectMake(0, 0, self.messagesView.frame.size.width, self.messagesView.frame.size.height);
    
    [self.navigationController presentViewController: controller animated: YES completion: nil];
}

# pragma mark - Instantiate View Controllers

- (UIViewController *)instantiateBaseMessageViewController{
    
    self.baseMessageViewController = (UALBaseMessageViewController *)[self.storyboard instantiateViewControllerWithIdentifier:@"UALBaseMessageViewController"];
    self.baseMessageViewController.delegate = self;
    return self.baseMessageViewController;
}

- (UIViewController *)instantiateFlightStatusMainViewController{
    
    self.flightStatusController = (UALFlightStatusMainViewController *)[self.storyboard instantiateViewControllerWithIdentifier:@"UALFlightStatusMainViewController"];
    self.flightStatusController.delegate = self;
    return self.flightStatusController;
}

# pragma mark - Delegate Methods

- (void)presentFlightStatusViewController{
        
    [self requestPresentationStyle: MSMessagesAppPresentationStyleExpanded];
}

- (void)expandFlightStatusMainViewController: (UITextField *)textField{
    
    [self requestPresentationStyle: MSMessagesAppPresentationStyleExpanded];
}

# pragma mark - All Helper Methods



@end
